version: '3.8'
services:
  api:
    image: quizard-app:backend-api  # Use the commit-tagged image in .prod override to be used in CI/CD workflow
    env_file:
      - .env
    environment:
      - APP_SERVICE=api
    depends_on:
      - rabbitmq
      - redis

  worker:
    image: quizard-app:backend-worker  # Use the commit-tagged image in .prod override to be used in CI/CD workflow
    env_file:
      - .env
    environment:
      - APP_SERVICE=worker
    depends_on:
      - api
      - redis
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672"  # Management interface
      - "5672:5672"   # RabbitMQ server
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  frontend:
    image: quizard-app:frontend  # Frontend image for production
