version: '3'

services:
  web:
    build: ./backend
    image: quizard:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app  # Mount the backend/src directory to /app in the container
    command: pipenv run python rest/app.py
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672" # Management interface
      - "5672:5672"   # RabbitMQ server
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}