openapi: 3.0.0
info:
  title: Quizard API POC
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1
paths:
  /flashcard/generate:
    post:
      tags: ['Flashcard generator']
      description: 'Generate flashcards for given input text with specified mode'
      requestBody:
        $ref: '#/components/requestBodies/generatorRequestBody'
      responses:
        201:
          description: 'The flashcards were generated successfully'
          content:
            application/json:
              schema:
                properties:
                  flashcards:
                    type: array
                    items:
                      $ref: '#/components/schemas/FlashCard'
                # we don't put the array directly into the body so that we can add additional information
        400:
          description: 'Bad request e.g. invalid mode was specified'
        500:
          description: 'Internal server error e.g. openai unreachable etc...'

components:
  requestBodies:
    generatorRequestBody:
      content:
        application/json:
          schema:
            properties:
              mode:
                type: string
                enum: ['practice', 'definitions', 'quiz', 'cloze']
                example: practice
              inputText:
                type: string
                description: 'The text for which flashcards should be generated'

  schemas:
    FlashCardType:
      type: string
      enum: ['UNKNOWN', 'DEFINITION', 'OPEN_ENDED', 'MULTIPLE_CHOICE', 'CLOZE']

    FlashCard:
      properties:
        id:
          type: integer
          example: 1
          description: The number of the flashcard, starting from 1
        frontSide:
          type: string
        backSide:
          type: string
        type:
          $ref: '#/components/schemas/FlashCardType'