name: Build and Deploy Quizard Backend API and Worker

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}

      - name: Build and push API Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/quizard-backend-api:latest

      - name: Deploy API Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_API_APP_NAME }}"
          token: "${{ secrets.CAPROVER_API_APP_TOKEN }}"
          image: "${{ github.repository_owner }}/quizard:api-latest"

  build-and-deploy-worker:
    runs-on: ubuntu-latest
    needs: build-and-deploy-api

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}

      - name: Build and push Worker Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/quizard-backend-worker:latest

      - name: Deploy Worker Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_WORKER_APP_NAME }}"
          token: "${{ secrets.CAPROVER_WORKER_APP_TOKEN }}"
          image: "${{ github.repository_owner }}/quizard:worker-latest"
